name: fluttermvvmtemplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  build_runner: ^1.10.0
  cached_network_image: ^3.0.0-nullsafety
  cupertino_icons: ^1.0.2
  # dio: ^4.0.0-prev3
  # vexana has a package
  easy_localization: ^3.0.0
  firebase-analytics
  firebase_analytics: any
  flutter_mobx: ^2.0.0-nullsafety.3

  flutter_mobx: ^2.0.0
  flutter_rating_bar: ^4.0.0
  master
  flutter_svg: ^0.21.0-nullsafety.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  kartal: ^2.1.0
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1+3
  mockito: any
  pedantic: ^1.11.0
  provider: ^5.0.0
  lottie: ^1.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  vexana: ^2.2.0
  webview_flutter: ^2.0.4
  logger: ^1.0.0

  architecture_theme:
    git:  https://github.com/VB10/architecture_theme.git
  architecture_widgets:
    path: module/architecture_widgets
  all_of_template:
    path: module/all_of_template
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/lang/
    - asset/svg/
    - asset/image/
    - asset/lottie/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
